name: Cron Deploy

on: 
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.1

    - name: Build
      run: |
        git clone https://github.com/apache/incubator-doris.git incubator-doris
        export BRANCH=master
        cp -R blogs/zh-CN/ incubator-doris/docs/zh-CN/blogs/
        cp -R blogs/en/ incubator-doris/docs/en/blogs/
        cp -R blogs/images/blogs/ incubator-doris/docs/.vuepress/public/images/
        cp -R versions.json incubator-doris/docs/.vuepress/public/
        cp -R sidebar/zh-CN/* incubator-doris/docs/.vuepress/sidebar/zh-CN/
        cp -R sidebar/en/* incubator-doris/docs/.vuepress/sidebar/en/
        cd incubator-doris/
        git fetch
        cd docs/
        find ./ -name "*.md" -exec sed -i -e 's/!\[\(.*\)\][(]\(.*\)[)]/<img \:src=\"$withBase\('\''\2'\''\)\" alt=\"\1\">/g' {} \;
        sed -i 's/en\///g' .vuepress/config.js
        sed -i 's/en\///g' .vuepress/theme/index.js
        sed -i "s/BUILDING_BRANCH\.length > 0/BUILDING_BRANCH\.length > 0 \&\& BUILDING_BRANCH !== 'master'/g" .vuepress/config.js
        sed -i 's/en\///g' en/README.md
        mv en/* ./
        mv .vuepress/sidebar/en/* .vuepress/sidebar/
        npm install -g increase-memory-limit
        increase-memory-limit
        export NODE_OPTIONS="--max-old-space-size=9144" && npm install && npm run build
        touch .vuepress/dist/.dummy
        ls .vuepress/dist/
        export DORIS_COMMIT=`git rev-parse HEAD`

    - name: Deploy Master
      run: |
        git fetch
        git checkout -b asf-site remotes/origin/asf-site
        /bin/bash remove-non-reserved-dir.sh
        cp -r incubator-doris/docs/.vuepress/dist/* ./
        rm -rf incubator-doris/
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated deployment with doris master"
        git push --verbose "https://${{ secrets.GITHUB_TOKEN }}@github.com/apache/incubator-doris-website.git" asf-site:asf-site

