name: Build and Deploy

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.1
    - name: Build
      run: |
        echo "ok"
        git clone https://github.com/apache/incubator-doris.git incubator-doris
        cd docs && npm install
        export BRANCH=master
        npm run build
        ls .vuepress/dist/
